//
// Created by CYK on 2024/12/17.
//

#ifndef DRV_AUTO_EXCHANGE_H
#define DRV_AUTO_EXCHANGE_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "Global_CFG.h"

/**
 * @brief 将两侧矿挪到中央
*/
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_X       (500.f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_Y       (70.f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_PITCH   (0.0f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_ROLL    (0.0f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_YAW     (0.f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_ARM_YAW (0.f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_ARM_PITCH (0.f)

#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_XYZ_VEL   (0.8f)
#define TAKING_SIDE_SUCKER_TO_CENTER_POSITION_RYP_VEL (0.1f)

//从左边吸盘上拿矿
#define TAKING_LEFT_SUCKER_POSITION_PRE_X   (330.f)
#define TAKING_LEFT_SUCKER_POSITION_PRE_Y   (70.f)
#define TAKING_LEFT_SUCKER_POSITION_PRE_Z   (90.f)
#define TAKING_LEFT_SUCKER_POSITION_PRE_PITCH  (0.f)

#define TAKING_LEFT_SUCKER_POSITION_ARM_YAW (30.0f)
#define TAKING_LEFT_SUCKER_POSITION_ARM_PITCH (0.0f)

#define TAKING_LEFT_SUCKER_POSITION_X   (330.f)
#define TAKING_LEFT_SUCKER_POSITION_Y   (230.f)
#define TAKING_LEFT_SUCKER_POSITION_Z  (90.f)

#define TAKING_LEFT_SUCKER_POSITION_YAW (90.0f)
#define TAKING_LEFT_SUCKER_POSITION_ROLL (0.0f)
#define TAKING_LEFT_SUCKER_POSITION_PITCH (5.0f)

#define TAKING_LEFT_SUCKER_POSITION_XYZ_VEL (0.8f)
#define TAKING_LEFT_SUCKER_POSITION_RYP_VEL (0.1f)
#define TAKING_LEFT_SUCKER_POSITION_ARM_VEL (0.1f)

#define TAKING_LEFT_SUCKER_POSITION_FINAL_Y   (300.f)
#define TAKING_LEFT_SUCKER_POSITION_FINAL_Y_VEL   (0.1f)

//从右边吸盘上拿矿
#define TAKING_RIGHT_SUCKER_POSITION_PRE_X   (330.f)
#define TAKING_RIGHT_SUCKER_POSITION_PRE_Y   (70.f)
#define TAKING_RIGHT_SUCKER_POSITION_PRE_Z   (90.f)
#define TAKING_RIGHT_SUCKER_POSITION_PRE_PITCH  (0.f)

#define TAKING_RIGHT_SUCKER_POSITION_ARM_YAW (-30.f)
#define TAKING_RIGHT_SUCKER_POSITION_ARM_PITCH (0.f)

#define TAKING_RIGHT_SUCKER_POSITION_X   (330.f)
#define TAKING_RIGHT_SUCKER_POSITION_Y   (-50.f)
#define TAKING_RIGHT_SUCKER_POSITION_Z  (90.f)

#define TAKING_RIGHT_SUCKER_POSITION_YAW (-90.f)
#define TAKING_RIGHT_SUCKER_POSITION_ROLL (0.0f)
#define TAKING_RIGHT_SUCKER_POSITION_PITCH (5.0f)

#define TAKING_RIGHT_SUCKER_POSITION_XYZ_VEL (0.8f)
#define TAKING_RIGHT_SUCKER_POSITION_RYP_VEL (0.1f)
#define TAKING_RIGHT_SUCKER_POSITION_ARM_VEL (0.1f)

#define TAKING_RIGHT_SUCKER_POSITION_FINAL_Y   (-160.f)
#define TAKING_RIGHT_SUCKER_POSITION_FINAL_Y_VEL   (0.1f)

#ifdef __cplusplus
}
#endif

#endif //DRV_AUTO_EXCHANGE_H
